name: myapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.1
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4
  characters: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/welcampage.jpg
    - assets/back.png
    - assets/event.png
    - assets/home.png
    - assets/search.png
    - assets/user.png
    - assets/icon/
